global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus Self
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres_exporter:9187']

    # Custom API exporter
  - job_name: 'custom_api'
    static_configs:
      - targets: ['host.docker.internal:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'external_apis'

  - job_name: 'custom_postgres'
    static_configs:
      - targets: ['host.docker.internal:9101']